CREATE TABLE `df_change_control` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `change_no` varchar(100) NOT NULL,
  `df_id` int(11) NOT NULL,
  `request_type` varchar(20) NOT NULL,
  `change_category` varchar(50) NOT NULL,
  `priority` varchar(20) NOT NULL,
  `source_of_change` varchar(50) NOT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `revision_no` varchar(100) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `change_summary` longtext NOT NULL,
  `impact_note` longtext DEFAULT NULL,
  `requested_from_department_id` int(11) NOT NULL DEFAULT 0,
  `attachment` varchar(255) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'OPEN',
  `created_by` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `closed_by` int(11) DEFAULT NULL,
  `closed_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_df_change_control_df_id` (`df_id`),
  KEY `idx_df_change_control_status` (`status`),
  KEY `idx_df_change_control_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `df_change_control_departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `change_id` int(11) NOT NULL,
  `department_id` int(11) NOT NULL,
  `department_head_id` int(11) NOT NULL DEFAULT 0,
  `planned_days` int(11) DEFAULT NULL,
  `target_date` date DEFAULT NULL,
  `assigned_user_id` int(11) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING_HEAD_ACTION',
  `notified_on` datetime DEFAULT NULL,
  `assigned_on` datetime DEFAULT NULL,
  `completed_on` datetime DEFAULT NULL,
  `completed_by` int(11) NOT NULL DEFAULT 0,
  `head_remarks` longtext DEFAULT NULL,
  `assignee_remarks` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_df_change_ctrl_dept_change_id` (`change_id`),
  KEY `idx_df_change_ctrl_dept_department_id` (`department_id`),
  KEY `idx_df_change_ctrl_dept_head_id` (`department_head_id`),
  KEY `idx_df_change_ctrl_dept_assigned_user_id` (`assigned_user_id`),
  KEY `idx_df_change_ctrl_dept_status` (`status`),
  KEY `idx_df_change_ctrl_dept_target_date` (`target_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `df_change_control_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `change_id` int(11) NOT NULL,
  `department_action_id` int(11) NOT NULL DEFAULT 0,
  `action_by` int(11) NOT NULL,
  `action_role` varchar(50) NOT NULL,
  `action_type` varchar(100) NOT NULL,
  `action_note` longtext DEFAULT NULL,
  `created_on` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_df_change_ctrl_history_change_id` (`change_id`),
  KEY `idx_df_change_ctrl_history_department_action_id` (`department_action_id`),
  KEY `idx_df_change_ctrl_history_action_by` (`action_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
