CREATE TABLE IF NOT EXISTS `task_punch_point_closure` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_record_id` int(11) NOT NULL DEFAULT 0,
  `source_task_record_id` int(11) NOT NULL DEFAULT 0,
  `task_id` int(11) NOT NULL DEFAULT 11,
  `df_id` int(11) NOT NULL DEFAULT 0,
  `po_id` int(11) NOT NULL DEFAULT 0,
  `assigned_user` int(11) NOT NULL DEFAULT 0,
  `point_title` varchar(255) NOT NULL,
  `point_description` text DEFAULT NULL,
  `department_id` int(11) NOT NULL DEFAULT 0,
  `delegate_to` int(11) NOT NULL DEFAULT 0,
  `due_date` date NOT NULL,
  `delegation_task_id` int(11) NOT NULL DEFAULT 0,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `added_on` datetime NOT NULL,
  `added_by` int(11) NOT NULL DEFAULT 0,
  `updated_on` datetime DEFAULT NULL,
  `updated_by` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `task_record_id` (`task_record_id`),
  KEY `source_task_record_id` (`source_task_record_id`),
  KEY `df_id` (`df_id`),
  KEY `delegate_to` (`delegate_to`),
  KEY `delegation_task_id` (`delegation_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
