CREATE TABLE `task_completion_control_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_record_id` int(11) NOT NULL,
  `df_id` int(11) NOT NULL DEFAULT 0,
  `task_id` int(11) NOT NULL DEFAULT 0,
  `action_type` varchar(50) NOT NULL,
  `old_task_status` int(11) NOT NULL DEFAULT 0,
  `new_task_status` int(11) NOT NULL DEFAULT 0,
  `old_task_completed_on` datetime NOT NULL,
  `new_task_completed_on` datetime NOT NULL,
  `old_task_completed_by` int(11) NOT NULL DEFAULT 0,
  `new_task_completed_by` int(11) NOT NULL DEFAULT 0,
  `old_remarks` longtext DEFAULT NULL,
  `new_remarks` longtext DEFAULT NULL,
  `old_df_status` int(11) NOT NULL DEFAULT 0,
  `new_df_status` int(11) NOT NULL DEFAULT 0,
  `action_note` text DEFAULT NULL,
  `changed_by` int(11) NOT NULL,
  `changed_on` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_task_completion_control_history_task_record` (`task_record_id`),
  KEY `idx_task_completion_control_history_df` (`df_id`),
  KEY `idx_task_completion_control_history_changed_by` (`changed_by`),
  KEY `idx_task_completion_control_history_changed_on` (`changed_on`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
