<form method="get" class="filters no-print" action="<?php echo ot_e(ot_link($action)); ?>">
<?php if ($action === '') { ?><div><label for="scope">Show</label><select id="scope" name="scope"><option value="mine">My requests / assignments</option><option value="visible" <?php echo empty($filters['mine']) ? 'selected' : ''; ?>>All accessible requests</option></select></div><?php } ?>
<div><label for="from">Start date from</label><input id="from" type="date" name="from" value="<?php echo ot_e($filters['from']); ?>"></div>
<div><label for="to">Start date to</label><input id="to" type="date" name="to" value="<?php echo ot_e($filters['to']); ?>"></div>
<div><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option><?php foreach ($statuses as $status) { ?><option value="<?php echo ot_e($status); ?>" <?php echo $filters['status'] === $status ? 'selected' : ''; ?>><?php echo ot_e(ot_status($status)); ?></option><?php } ?></select></div>
<div><label for="df-filter">DF No.</label><select id="df-filter" name="df_id"><option value="">All DFs</option><?php foreach ($options['dfs'] as $df) { ?><option value="<?php echo (int)$df['id']; ?>" <?php echo (int)$filters['df_id']===(int)$df['id'] ? 'selected' : ''; ?>><?php echo ot_e($df['df_no']); ?></option><?php } ?></select></div>
<div><label for="person-filter">Person / labour name</label><input id="person-filter" name="person" maxlength="200" value="<?php echo ot_e($filters['person']); ?>" placeholder="Search any worker name"></div>
<div><label for="employee">PMS user</label><select id="employee" name="employee_id"><option value="">All accessible employees</option><?php foreach ($options['employees'] as $employee) { ?><option value="<?php echo (int) $employee['user_id']; ?>" <?php echo (int) $filters['employee_id'] === (int) $employee['user_id'] ? 'selected' : ''; ?>><?php echo ot_e($employee['first_name'] . ' ' . $employee['last_name']); ?></option><?php } ?></select></div>
<div><label for="department">Department</label><select id="department" name="department_id"><option value="">All accessible departments</option><?php foreach ($options['departments'] as $department) { ?><option value="<?php echo (int) $department['department_id']; ?>" <?php echo (int) $filters['department_id'] === (int) $department['department_id'] ? 'selected' : ''; ?>><?php echo ot_e($department['department']); ?></option><?php } ?></select></div>
<?php if ($action === 'reports') { ?><div><label for="group">Group summary by</label><select id="group" name="group"><option value="employee">Person</option><option value="df" <?php echo $group === 'df' ? 'selected' : ''; ?>>DF No.</option><option value="department" <?php echo $group === 'department' ? 'selected' : ''; ?>>Department</option><option value="day" <?php echo $group === 'day' ? 'selected' : ''; ?>>Day</option></select></div><?php } ?>
<button type="submit">Apply filters</button><a class="button secondary" href="<?php echo ot_e(ot_link($action)); ?>">Reset</a>
</form>
