<?php $group_labels = array('employee'=>'Person', 'department'=>'Department', 'df'=>'DF', 'day'=>'Day'); $group_label = isset($group_labels[$group]) ? $group_labels[$group] : 'Person'; ?>
<div class="heading"><div><div class="eyebrow">Hours, approvals and overhead cost</div><h1>Overtime reports</h1><p class="muted">DF, person, department and day-wise summaries, including manual workers.</p></div><div class="no-print"><a class="button" href="<?php echo ot_e(ot_link('export', $filters)); ?>">Export details CSV</a> <button type="button" class="secondary" data-print>Print report</button></div></div>
<div class="notice">Period: <?php echo ot_e($filters['from'] ?: 'All past dates'); ?> → <?php echo ot_e($filters['to'] ?: 'All future dates'); ?>, by overtime <strong>start date</strong>. Only requests you can access are included. Totals are person-hours: 4 people × 2 hours = 8 hours. Requested totals include rejected and cancelled requests; approved totals include only final approvals. Cost is the rate stored on each person row when the overtime was raised and again when it was approved, so later rate changes do not restate finished overtime.<span class="print-only">Printed detail page <?php echo (int) $page; ?>. Use CSV for the full request list.</span></div>
<?php $this->load->view('overtime/_stats', compact('summary')); ?>
<div class="card no-print"><?php $action = 'reports'; $this->load->view('overtime/_filters', compact('action','filters','options','statuses','group')); ?></div>
<div class="card"><h2><?php echo ot_e($group_label); ?> summary</h2>
<?php if ($group === 'day') { ?><p class="muted">One row per overtime date. "Occasions" counts separate overtime requests, so a single night covering eight people counts once.</p><?php } ?>
<div class="table-wrap"><table>
<thead><tr><th><?php echo ot_e($group_label); ?></th><th class="num">Occasions</th><th class="num">Person entries</th><th class="num">Requested hours</th><th class="num">Pending hours</th><th class="num">Approved hours</th><th class="num">Cost awaiting approval</th><th class="num">Approved cost</th></tr></thead>
<tbody><?php foreach ($groups as $row) { ?><tr><td><?php echo ot_e($row['label']); ?> </td><td class="num"><?php echo (int) $row['request_count']; ?></td><td class="num"><?php echo (int) $row['total']; ?></td><td class="num"><?php echo ot_hours($row['requested_minutes']); ?></td><td class="num"><?php echo ot_hours($row['pending_minutes']); ?></td><td class="num"><?php echo ot_hours($row['approved_minutes']); ?></td><td class="num">₹ <?php echo ot_money($row['pending_cost']); ?></td><td class="num">₹ <?php echo ot_money($row['approved_cost']); ?></td></tr><?php } ?>
<?php if (!$groups) { ?><tr><td colspan="8" class="empty">No overtime requests in this selection.</td></tr><?php } ?></tbody>
<?php if ($groups) { ?><tfoot><tr><th>Total for this selection</th><th class="num"><?php echo (int) $summary['request_count']; ?></th><th class="num"><?php echo (int) $summary['total']; ?></th><th class="num"><?php echo ot_hours($summary['requested_minutes']); ?></th><th class="num"><?php echo ot_hours($summary['pending_minutes']); ?></th><th class="num"><?php echo ot_hours($summary['approved_minutes']); ?></th><th class="num">₹ <?php echo ot_money($summary['pending_cost']); ?></th><th class="num">₹ <?php echo ot_money($summary['approved_cost']); ?></th></tr></tfoot><?php } ?>
</table></div></div>
<div class="card"><h2>Overtime detail — one row per person</h2><?php $this->load->view('overtime/_table', compact('rows','summary','filters','page','action','group')); ?></div>
