<?php $people = $request['assignments']; $people_count = max(1,count($people)); ?>
<div class="heading"><div><div class="eyebrow">Overtime request</div><h1><?php echo ot_e($request['request_code']); ?></h1><p><span class="badge <?php echo ot_e($request['status']); ?>"><?php echo ot_e(ot_status($request['status'])); ?></span></p></div><button class="secondary no-print" type="button" data-print>Print request</button></div>
<div class="card"><h2>Approval progress</h2><div class="steps"><div class="step done"><strong>1. Request raised</strong><br><?php echo ot_e($request['first_name'].' '.$request['last_name']); ?><br><?php echo ot_e($request['created_at']); ?></div><div class="step <?php echo $request['admin_decided_at'] ? 'done' : ''; ?>"><strong>2. Shubham Sharma approval</strong><br><?php echo ot_e($request['admin_decided_at'] ?: 'Awaiting decision'); ?></div><div class="step <?php echo $request['status'] === 'APPROVED' ? 'done' : ''; ?>"><strong>3. Overtime assigned</strong><br><?php echo $request['status'] === 'APPROVED' ? 'Approved for '.$people_count.' people' : 'Requires approval'; ?></div></div><small>The status and audit history record approval, rejection, and cancellation decisions. Older requests retain their original history.</small></div>
<div class="card"><div class="grid"><div><dl><dt>DF No.</dt><dd><?php echo ot_e($request['df_no'] ?: 'Legacy request — no DF linked'); ?></dd><dt>Requested by / Department</dt><dd><?php echo ot_e($request['first_name'].' '.$request['last_name'].' / '.$request['department']); ?></dd><dt>Work reference</dt><dd><?php echo ot_e($request['work_reference'] ?: '—'); ?></dd></dl></div><div><dl><dt>Start → End</dt><dd><?php echo ot_e($request['start_at'].' → '.$request['end_at']); ?></dd><dt>Hours per person</dt><dd><?php echo ot_hours($request['requested_minutes']); ?><?php if ($request['break_minutes']) { ?> (excluding <?php echo (int)$request['break_minutes']; ?> break minutes)<?php } ?></dd><dt>Total requested / Approved person-hours</dt><dd><?php echo ot_hours($people_count*$request['requested_minutes']); ?> / <?php echo $request['status']==='APPROVED' ? ot_hours($people_count*$request['requested_minutes']) : '0.00'; ?></dd></dl></div></div><h3>Reason and planned work</h3><div class="preserve"><?php echo ot_e($request['reason']); ?></div></div>
<div class="card"><h2>People selected for overtime</h2><div class="table-wrap"><table><thead><tr><th>Person</th><th>Type</th><th>Hours</th><th class="num">Cost</th><th>Assignment</th></tr></thead><tbody>
<?php if (!$people) $people = array(array('person_name'=>$request['first_name'].' '.$request['last_name'], 'user_id'=>$request['employee_id'], 'assigned_at'=>$request['status']==='APPROVED' ? $request['admin_decided_at'] : null, 'hourly_rate'=>0, 'cost_amount'=>0)); ?>
<?php foreach ($people as $person) { ?><tr><td><?php echo ot_e($person['person_name']); ?></td><td><?php echo $person['user_id'] ? 'PMS user #'.(int)$person['user_id'] : 'Manual worker'; ?></td><td><?php echo ot_hours($request['requested_minutes']); ?></td><td class="num"><?php if ((float) $person['hourly_rate'] > 0) { ?>&#8377; <?php echo ot_money($person['cost_amount']); ?><br><small>@ &#8377;<?php echo ot_money($person['hourly_rate']); ?>/hr</small><?php } else { ?><span class="muted">No rate</span><?php } ?></td><td><?php echo $request['status']==='APPROVED' ? 'Assigned · '.ot_e($person['assigned_at']) : ot_e(ot_status($request['status'])); ?></td></tr><?php } ?>
</tbody></table></div></div>
<?php if ($can_decide) { ?><div class="card no-print"><h2>Shubham Sharma — approval decision</h2><form method="post" action="<?php echo ot_e(ot_link('decide/'.(int)$request['id'])); ?>">
<?php $this->load->view('overtime/_token',compact('csrf')); ?><label for="decision">Decision *</label><select id="decision" name="decision" required><option value="">Choose a decision</option><option value="APPROVE">Approve and assign overtime</option><option value="REJECT">Reject request</option></select><label for="decision-note" style="margin-top:14px">Remarks (optional for approval or rejection)</label><textarea id="decision-note" name="note" maxlength="4000"></textarea><button type="submit">Save decision</button></form></div><?php } ?>
<?php if ($can_cancel) { ?><details class="card no-print"><summary>Cancel this request</summary><p class="muted">Approved overtime can only be cancelled before its start time.</p><form method="post" action="<?php echo ot_e(ot_link('decide/'.(int)$request['id'])); ?>" data-confirm="Cancel this overtime request?">
<?php $this->load->view('overtime/_token',compact('csrf')); ?><input type="hidden" name="decision" value="CANCEL"><label for="cancel-note">Cancellation reason *</label><textarea id="cancel-note" name="note" minlength="5" maxlength="4000" required></textarea><button class="danger" type="submit">Cancel request</button></form></details><?php } ?>
<div class="card"><h2>Audit history</h2><div class="table-wrap"><table><thead><tr><th>When / Who</th><th>Action</th><th>Status transition</th><th>Remarks</th></tr></thead><tbody><?php foreach ($history as $event) { ?><tr><td><?php echo ot_e($event['created_at']); ?><br><?php echo ot_e($event['first_name'].' '.$event['last_name']); ?> <small>#<?php echo (int)$event['actor_id']; ?></small></td><td><?php echo ot_e($event['action']); ?></td><td><?php echo ot_e($event['from_status'] ? ot_status($event['from_status']).' → ' : ''); ?><?php echo ot_e(ot_status($event['to_status'])); ?></td><td class="preserve"><?php echo ot_e($event['note']); ?></td></tr><?php } ?></tbody></table></div></div>
