<?php

// Include the qrlib file
include 'phpqrcode/qrlib.php';

// $text variable has data for QR
$text = "https://easemysale.com/hpcl/Open_leads/open_lead/MQ==";

// $path = SITE_ROOT.'qrimages/';
// $name=time().".png";
// $file = $path.$name;
//   // $ecc stores error correction capability('L')
// $ecc = 'L';
// $pixel_Size = 5;
// $frame_Size = 5;
// $matrixPointSize=6;
// // Generates QR Code and Stores it in directory given
// //QRcode::png($text, $file, $ecc, $pixel_Size, $frame_Size);
//  QRcode::png($text,$file , $ecc, $matrixPointSize, 2);
// $QR_width = imagesx($file);      //QR code picture width
// $QR_height = imagesy($file);
// $logo=SITE_ROOT.'assets/images/logo_mitr.png';
// $logo_width = imagesx($logo);    //logo picture width
// $logo_height = imagesy($logo);   //logo image height
// $logo_qr_width = $QR_width / 4;   //Width of logo after combination (1 / 5 of QR code)
// $scale = $logo_width/$logo_qr_width;  //Width scaling ratio of logo (own width / combined width)
// $logo_qr_height = $logo_height/$scale; //Height of logo after combination
// $from_width = ($QR_width - $logo_qr_width) / 2;  //Coordinate point of upper left corner of logo after combination
// imagecopyresampled($file, $logo, $from_width, $from_width, 0, 0, $logo_qr_width,$logo_qr_height, $logo_width, $logo_height);



$value = 'https://easemysale.com/hpcl/Open_leads/open_lead/MQ==';//QR code content
$errorCorrectionLevel = 'H';  //Fault tolerance level
$matrixPointSize = 10;      //Generate picture size

//Generate QR code picture
$path = SITE_ROOT.'qrimages/';//Directory of generated QR code
if(!file_exists($path)){
mkdir($path, 0700,true);
}
$name=time().".png";
//Generated QR code file name
$fileName = $path.$name;//1. Path of QR code file generated by assembly
QRcode::png($value,$fileName , $errorCorrectionLevel, $matrixPointSize, 2);
$logo = SITE_ROOT.'qrimages/logo_mitr.png'; //logo picture ready

$QR = $fileName;				//Generated original QR code picture file
if (file_exists($logo)) {
$QR = imagecreatefromstring(file_get_contents($QR));    //Target image connection resource.
$logo = imagecreatefromstring(file_get_contents($logo));  //Source image connection resource.
$QR_width = imagesx($QR);      //QR code picture width
$QR_height = imagesy($QR);     //QR code image height
$logo_width = imagesx($logo);    //logo picture width
$logo_height = imagesy($logo);   //logo image height
$logo_qr_width = $QR_width / 4;   //Width of logo after combination (1 / 5 of QR code)
$scale = $logo_width/$logo_qr_width;  //Width scaling ratio of logo (own width / combined width)
$logo_qr_height = $logo_height/$scale; //Height of logo after combination
$from_width = ($QR_width - $logo_qr_width) / 2;  //Coordinate point of upper left corner of logo after combination
//Recombine and resize pictures
/*
* imagecopyresampled() Copy a square area from one image (source image) to another
*/
imagecopyresampled($QR, $logo, $from_width, $from_width, 0, 0, $logo_qr_width,$logo_qr_height, $logo_width, $logo_height);
}
  
$file1=page_url.'qrimages/'.$name;
// Displaying the stored QR code from directory
echo "<center><img src='".$file1."'></center>";


