<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo sitetitle; ?> - Order Spare Quotations</title>
<link href="<?php echo assets_url; ?>css/bootstrap.min.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/core.css" rel="stylesheet">
<link href="<?php echo assets_url; ?>css/components.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/icons.css" rel="stylesheet">
<link href="<?php echo assets_url; ?>css/menu.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/responsive.css" rel="stylesheet">
<style>body{background:#f4f7fb}.quote-hero{background:linear-gradient(135deg,#315b9d,#17243b);color:#fff;border-radius:16px;padding:24px;margin:20px 0}.card-box{border-radius:14px;box-shadow:0 5px 18px rgba(0,0,0,.06)}.status{padding:6px 12px;border-radius:20px;font-weight:700}.status-Won{background:#dff5e7;color:#16813b}.status-Quoted{background:#e5efff;color:#225da8}.status-Superseded{background:#eee;color:#777}</style></head>
<body><header id="topnav"><?php $this->load->view('common/nav-menu'); ?></header><div class="wrapper"><div class="container-fluid">
<div class="quote-hero"><div class="row"><div class="col-md-8"><h3 style="margin-top:0">Spare Quotations for This Order</h3>
<p style="margin:0;opacity:.9"><strong><?php echo html_escape($po->company_name); ?></strong> &nbsp;|&nbsp; PO: <?php echo html_escape($po->pono ?: '-'); ?> &nbsp;|&nbsp; DF: <?php echo html_escape($po->df_number ?: '-'); ?></p></div>
<div class="col-md-4 text-right"><a class="btn btn-success" href="<?php echo page_url; ?>Order_spare_quotation/create/<?php echo (int)$po->id; ?>"><i class="fa fa-plus"></i> Create Quotation</a>
<a class="btn btn-default" href="<?php echo page_url; ?>Task/myreceivedpolist"><i class="fa fa-arrow-left"></i> My Orders</a></div></div></div>
<?php echo $this->session->flashdata('message'); ?>
<div class="card-box table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>#</th><th>Quotation</th><th>Date</th><th>Revision</th><th class="text-right">Quotation Value</th><th>Status</th><th>Won PO</th><th>Actions</th></tr></thead><tbody>
<?php if ($quotes) { foreach ($quotes as $i=>$q) { ?><tr><td><?php echo $i+1; ?></td><td><strong><?php echo html_escape($q->quotation_no); ?></strong></td><td><?php echo date('d-M-Y',strtotime($q->quotation_date)); ?></td><td><?php echo $q->revision_no ? 'R'.(int)$q->revision_no : 'Original'; ?></td>
<td class="text-right"><?php echo html_escape($q->currency); ?> <?php echo number_format($q->grand_total,2); ?></td><td><span class="status status-<?php echo html_escape($q->status); ?>"><?php echo html_escape($q->status); ?></span></td>
<td><?php if ($q->status==='Won') { echo html_escape($q->won_po_no).'<br><strong>'.html_escape($q->currency).' '.number_format($q->won_order_value,2).'</strong>'; if($q->won_po_attachment){ ?><br><a target="_blank" href="<?php echo base_url('uploads/order_spare_po/'.$q->won_po_attachment); ?>"><i class="fa fa-paperclip"></i> Attachment</a><?php }} else echo '-'; ?></td>
<td><a class="btn btn-primary btn-xs" href="<?php echo page_url; ?>Order_spare_quotation/view/<?php echo (int)$q->id; ?>"><i class="fa fa-eye"></i> View</a> <a class="btn btn-info btn-xs" href="<?php echo page_url; ?>Order_spare_quotation/revise/<?php echo (int)$q->id; ?>"><i class="fa fa-copy"></i> Revise</a>
<?php if($q->status !== 'Won' && $q->status !== 'Superseded'){ ?><button class="btn btn-success btn-xs" data-toggle="modal" data-target="#won-<?php echo (int)$q->id; ?>"><i class="fa fa-trophy"></i> Order Won</button><?php } ?></td></tr>
<div class="modal fade" id="won-<?php echo (int)$q->id; ?>"><div class="modal-dialog"><form method="post" enctype="multipart/form-data" action="<?php echo page_url; ?>Order_spare_quotation/mark_won/<?php echo (int)$q->id; ?>"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4>Attach Won PO - <?php echo html_escape($q->quotation_no); ?></h4></div><div class="modal-body"><div class="row">
<div class="col-md-6 form-group"><label>PO Number *</label><input name="won_po_no" class="form-control" required></div><div class="col-md-6 form-group"><label>PO Date *</label><input type="date" name="won_po_date" value="<?php echo date('Y-m-d'); ?>" class="form-control" required></div>
<div class="col-md-6 form-group"><label>Order Value *</label><input type="number" min="0" step="0.01" name="won_order_value" value="<?php echo html_escape($q->grand_total); ?>" class="form-control" required></div><div class="col-md-6 form-group"><label>PO Attachment</label><input type="file" name="po_attachment" accept=".pdf,.jpg,.jpeg,.png" class="form-control"></div>
<div class="col-md-12 form-group"><label>Remarks</label><textarea name="won_remarks" class="form-control"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-success"><i class="fa fa-check"></i> Confirm Order Won</button></div></div></form></div></div>
<?php }} else { ?><tr><td colspan="8" class="text-center text-muted" style="padding:35px">No spare quotation has been created for this order.</td></tr><?php } ?></tbody></table></div>
</div></div><?php $this->load->view('common/footer'); ?><script src="<?php echo assets_url; ?>js/jquery.min.js"></script><script src="<?php echo assets_url; ?>js/bootstrap.min.js"></script></body></html>
