<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?php echo html_escape($quote->quotation_no); ?></title>
<link href="<?php echo assets_url; ?>css/bootstrap.min.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/core.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/components.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/icons.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/menu.css" rel="stylesheet"><link href="<?php echo assets_url; ?>css/responsive.css" rel="stylesheet">
<style>body{background:#eef2f7}.paper{background:#fff;max-width:1000px;margin:25px auto;padding:42px;box-shadow:0 6px 24px rgba(0,0,0,.09)}.head{border-bottom:3px solid #294d7c;margin-bottom:25px}.total-row{font-size:18px;background:#eaf2fc}@media print{header,.no-print,footer{display:none!important}body{background:#fff}.wrapper{padding-top:0}.paper{box-shadow:none;margin:0;max-width:none}}</style></head><body><header id="topnav"><?php $this->load->view('common/nav-menu'); ?></header><div class="wrapper"><div class="paper">
<div class="no-print text-right"><a class="btn btn-default" href="<?php echo page_url; ?>Order_spare_quotation/index/<?php echo (int)$po->id; ?>">Back</a> <button class="btn btn-primary" onclick="window.print()"><i class="fa fa-print"></i> Print / Save PDF</button></div>
<div class="head"><div class="row"><div class="col-xs-7"><h2>SPARE PARTS QUOTATION</h2><p>Shubham Flexible Packaging Machines Pvt. Ltd.</p></div><div class="col-xs-5 text-right"><h4><?php echo html_escape($quote->quotation_no); ?></h4><p><?php echo date('d-M-Y',strtotime($quote->quotation_date)); ?></p></div></div></div>
<div class="row"><div class="col-xs-7"><strong>To</strong><h4><?php echo html_escape($po->company_name); ?></h4><p>Attention: <?php echo html_escape($quote->attention ?: '-'); ?></p></div><div class="col-xs-5"><p><strong>Against received PO:</strong> <?php echo html_escape($po->pono ?: '-'); ?></p><p><strong>Machine / DF:</strong> <?php echo html_escape($po->df_number ?: '-'); ?></p><p><strong>Status:</strong> <?php echo html_escape($quote->status); ?></p></div></div>
<p><strong>Subject:</strong> <?php echo html_escape($quote->subject ?: 'Quotation for spare parts'); ?></p>
<table class="table table-bordered"><thead><tr><th>#</th><th>Description</th><th>HSN</th><th class="text-right">Qty</th><th>Unit</th><th class="text-right">Rate</th><th class="text-right">Disc.</th><th class="text-right">GST</th><th class="text-right">Total</th></tr></thead><tbody><?php foreach($items as $i=>$item){ ?><tr><td><?php echo $i+1; ?></td><td><?php echo nl2br(html_escape($item->item_description)); ?></td><td><?php echo html_escape($item->hsn_code); ?></td><td class="text-right"><?php echo number_format($item->quantity,3); ?></td><td><?php echo html_escape($item->unit); ?></td><td class="text-right"><?php echo number_format($item->unit_rate,2); ?></td><td class="text-right"><?php echo number_format($item->discount_percent,2); ?>%</td><td class="text-right"><?php echo number_format($item->gst_percent,2); ?>%</td><td class="text-right"><?php echo number_format($item->line_total,2); ?></td></tr><?php } ?></tbody></table>
<div class="row"><div class="col-xs-7"><p><strong>Payment:</strong> <?php echo html_escape($quote->payment_terms ?: '-'); ?></p><p><strong>Validity:</strong> <?php echo html_escape($quote->validity ?: '-'); ?></p><p><strong>Delivery:</strong> <?php echo html_escape($quote->delivery_terms ?: '-'); ?></p><p><?php echo nl2br(html_escape($quote->notes)); ?></p></div><div class="col-xs-5"><table class="table"><tr><td>Basic Total</td><td class="text-right"><?php echo number_format($quote->sub_total,2); ?></td></tr><tr><td>Discount</td><td class="text-right"><?php echo number_format($quote->discount_total,2); ?></td></tr><tr><td>GST</td><td class="text-right"><?php echo number_format($quote->gst_total,2); ?></td></tr><tr class="total-row"><th>Grand Total (<?php echo html_escape($quote->currency); ?>)</th><th class="text-right"><?php echo number_format($quote->grand_total,2); ?></th></tr></table></div></div>
</div></div><script src="<?php echo assets_url; ?>js/jquery.min.js"></script><script src="<?php echo assets_url; ?>js/bootstrap.min.js"></script></body></html>
